APP_NAME: 'Clinsyte'
SMTP_USERNAME: 'testcodebrahma@gmail.com'
SMTP_PASSWORD: 'tqzfsgnctudiqfid'
APP_HOST: 'localhost:3000'
TWILLIO_ACCOUNT_SID: 'ACfcce8072159e0481bad771f7b6c0751e'
TWILLIO_AUTH_TOKEN: 'c0459f41373fc8d412fdd6dae4279a88'
TWILLIO_PHONE_NUMBER: '+19723250276'
VERIFICATION_REDIRECT_URL: '/'
SECRET_KEY_BASE: 'c82df0b558c87f601aed68a45e51f41cfb7c3ae8880a43af5dcc6d88c9ccf6327b738ccc999b7cb186a693a99b9ecfe9150b1d48a8ee7e2244005c30db4e6965'
# ADMIN CREDENTIALS
ADMIN_EMAIL: 'kamesh@codebrahma.com'
ADMIN_PASSWORD: 'codebrahma123'
ADMIN_FIRSTNAME: 'KAMESHWARAN'
ADMIN_LASTNAME: 'SACHITHANANTHAM'
ADMIN_GENDER: 'Male'
ADMIN_BIRTHDATE: '15/06/1993'
ADMIN_ETHNICITY: 'Asian'
ADMIN_COUNTRY_CODE: '+91'
ADMIN_PHONENUMBER: '9980789192'
# Reminder flow config
REMINDER_TIME_GAP: '15'
SNOOZE_TIME_GAP: '1'
# Rails admin theme
RAILS_ADMIN_THEME: 'rollincode'
# FAYE SERVER CONFIG
FAYE_SERVER: 'https://clinsyte-faye.herokuapp.com/faye'